# Colours from: https://github.com/alebelcor/alacritty-snazzy/blob/master/snazzy.yml
draw_bold_text_with_bright_colors: true

colors:

  primary:
    background: '0x282a36'
    foreground: '0xeff0eb'

  cursor:
    cursor: '0x97979b'

  selection:
    text:       '0x282a36'
    background: '0xfeffff'

  normal:
    black:   '0x282a36'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'

  bright:
    black:   '0x686868'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xeff0eb'

# Font configuration (changes require restart)
font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
 
  size: 12

# Mod + N opens another terminal in the same directory
key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }

